In [1]:
import random
from datetime import datetime
from datetime import timedelta

import pandas as pd
from faker import Faker

In [2]:
Faker.seed(42)
fake = Faker(['ko_KR', 'en_US'])

In [3]:
data = [{
    "id": i + 1,
    "name": fake.name(),
    "age": fake.random_int(min=20, max=65),
    "weight": fake.random_int(min=10, max=250),
    "height": fake.random_int(min=10, max=250),
    "gender": random.choice(['남성', '여성']),
    "address": fake.address(),
    "job": fake.job(),
    "email": fake.email(),
    "signup": (datetime.now() - timedelta(days=random.randint(0, 365))).date().isoformat()
} for i in range(10000)]

### Pandas Display 설정

In [4]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_colwidth", 50)
pd.set_option("display.width", 200)
pd.set_option("display.expand_frame_repr", False)

### Pandas DataFrame 만들기

In [5]:
source_dataframe = pd.DataFrame(data)
source_dataframe.head(1)

   id name  age  weight  height gender              address           job                  email      signup
0   1  이상현   63     161      18     여성  인천광역시 성북구 잠실길 지하430  중식 주방장 및 조리사  blakeerik@example.com  2025-12-28

In [6]:
column = ["id", "name", "age", "height", "weight", "gender", "address", "job", "email", "signup"]
source_dataframe = pd.DataFrame(data, columns=column)
source_dataframe.head(1)

   id name  age  height  weight gender              address           job                  email      signup
0   1  이상현   63      18     161     여성  인천광역시 성북구 잠실길 지하430  중식 주방장 및 조리사  blakeerik@example.com  2025-12-28

### Pandas DataFrame 파일 쓰기

In [7]:
source_dataframe.to_csv("./data/customers.csv", index=False, header=False, sep="|")
source_dataframe.to_json("./data/customers.json", orient="records")
source_dataframe.to_pickle("./data/customers.pickle")
source_dataframe.to_parquet("./data/customers.parquet")

### Pandas DataFrame 파일 읽기

In [8]:
# dataframe = pd.read_csv("./data/customers.csv", header=None, sep="|", names=column)
# dataframe = pd.read_json("./data/customers.json")
# dataframe = pd.read_parquet("./data/customers.parquet")
dataframe = pd.read_pickle("./data/customers.pickle")

In [9]:
pd.set_option("display.max_colwidth", None)
dataframe[["address", "email"]].head()
dataframe.head(1)

   id name  age  height  weight gender              address           job                  email      signup
0   1  이상현   63      18     161     여성  인천광역시 성북구 잠실길 지하430  중식 주방장 및 조리사  blakeerik@example.com  2025-12-28

### Pandas Apply 맛보기

In [10]:
def calc_bmi(row):
    height_m = row["height"] / 100
    return round(row["weight"] / (height_m ** 2), 2)


dataframe["bmi"] = dataframe.apply(calc_bmi, axis=1)
dataframe.head(1)

   id name  age  height  weight gender              address           job                  email      signup      bmi
0   1  이상현   63      18     161     여성  인천광역시 성북구 잠실길 지하430  중식 주방장 및 조리사  blakeerik@example.com  2025-12-28  4969.14

In [13]:
storage_options = {"client_kwargs": {"endpoint_url": "http://localhost:9000"}}
orders = pd.read_parquet("s3://mmix-prod-dataengineer-datalakehouse/mmix/customers/customers.parquet", storage_options=storage_options)
orders.head(10)

   id name  age  weigh  height gender                         address                   job                      email      signup
0   2  송민수   44    136     238     남성  세종특별자치시 성북구 도산대가 지하576 (상현김마을)         금속 / 재료공학 시험원             di@example.com  2025-03-15
1   3  장명숙   28     15     187     여성     대전광역시 은평구 압구정거리 103 (성호박김동)               자동차 조립원           icoe@example.org  2025-02-27
2   4  김미영   42     46      92     남성        서울특별시 광진구 삼성가 433 (춘자이리)           섀시 조립 및 설치원    simyeongsug@example.net  2025-11-30
3   5  권현지   20    237      98     남성               울산광역시 중구 영동대가 852           간판 제작 및 설치원         bseong@example.org  2025-05-14
4   6  오미정   64    168     234     여성  경상남도 부천시 오정구 개포216가 116 (지현이읍)               인쇄기 조작원     gwangsugim@example.net  2025-02-07
5   7  김지훈   51    205     148     남성   전라북도 성남시 분당구 선릉가 345-3 (영자박동)          매표원 및 복권 판매원        jieun55@example.net  2025-12-05
6   8  하도현   21    180     109     여성          제주특별자치도 홍성군 논현4로 지하453             무용가 및 안무가      iyeongjin@example.net  2025-12-29
7   9  심성호   60    126     160     여성               강원도 부천시 선릉5거리 612        웹 및 멀티미디어 디자이너       munyujin@example.com  2025-09-09
8  10  박준영   28    156     161     남성          광주광역시 강동구 학동02길 354-77                   경호원  baeggyeongsug@example.net  2025-03-26
9  11  최진우   27     57      88     여성            서울특별시 강남구 양재천가 지하349  기타 섬유 및 가죽 관련 기능 종사원           mgim@example.net  2025-09-01